@{
  # Advanced Installer
  'AccountResetInstaller.zip'                                  = 'Installers\AdvancedInstaller\Cjwdev.ADAccountResetTool\Current\AccountResetInstaller.zip'
  'bm-14.2.0.exe'                                              = 'Installers\AdvancedInstaller\MatthiasZronek.BenchMate\14.2.0\bm-14.2.0.exe'
  'DragonframeLicenseManager_3.0.3-Setup.exe'                  = 'Installers\AdvancedInstaller\DZEDSystems.DragonframeLicenseManager\3.0.3\DragonframeLicenseManager_3.0.3-Setup.exe'
  'fxsound_setup-1.2.10.0.exe'                                 = 'Installers\AdvancedInstaller\FxSound.FxSound\1.2.10.0\fxsound_setup-1.2.10.0.exe'
  'fxsound_setup.arm64-1.2.10.0.exe'                           = 'Installers\AdvancedInstaller\FxSound.FxSound\1.2.10.0\fxsound_setup.arm64-1.2.10.0.exe'
  'Setup.DVLS.Console.2026.1.15.0.exe'                         = 'Installers\AdvancedInstaller\Devolutions.DevolutionsLauncher\2026.1.15.0\Setup.DVLS.Console.2026.1.15.0.exe'
  'teracopy3.9.exe'                                            = 'Installers\AdvancedInstaller\CodeSector.TeraCopy\3.9\teracopy3.9.exe'
  'TINspireComputerLink-3.9.0.455.exe'                         = 'Installers\AdvancedInstaller\TexasInstruments.TI-Nspire.ComputerLink\3.9.0.455\TINspireComputerLink-3.9.0.455.exe'

  # Burn
  'Enpass-setup.exe'                                           = 'Installers\Burn\Sinew.Enpass\Current\Enpass-setup.exe'
  'GrammarlyAddInSetup6.8.263.exe'                             = 'Installers\Burn\Grammarly.Grammarly.Office\6.8.263\GrammarlyAddInSetup6.8.263.exe'
  'JabraDirectSetup.exe'                                       = 'Installers\Burn\Jabra.Direct\Current\JabraDirectSetup.exe'
  'Proton Drive Setup 3.0.2.exe'                               = 'Installers\Burn\Proton.ProtonDrive\3.0.2\Proton Drive Setup 3.0.2.exe'
  'python-3.13.9-amd64.exe'                                    = 'Installers\Burn\Python.Python.3.13\3.13.9\python-3.13.9-amd64.exe'
  'python-3.14.6-amd64.exe'                                    = 'Installers\Burn\Python.Python.3.14\3.14.6\python-3.14.6-amd64.exe'

  # Chromium Setup, Omaha, and Google Updater
  '360.360Ent-13.3.4100.143-x86.exe'                           = 'Installers\ChromiumSetup\360.360Ent\13.3.4100.143\360.360Ent-13.3.4100.143-x86.exe'
  'BraveBrowserBetaSetup-1.93.120.exe'                         = 'Installers\ChromiumSetup\Brave.Brave.Beta\1.93.120\BraveBrowserBetaSetup-1.93.120.exe'
  'BraveOriginBetaSetup-1.93.120.exe'                          = 'Installers\ChromiumSetup\Brave.BraveOrigin.Beta\1.93.120\BraveOriginBetaSetup-1.93.120.exe'
  'ChromeOnlineSetup.exe'                                      = 'Installers\ChromiumSetup\Google.Chrome.EXE\Current\ChromeOnlineSetup.exe'
  'GoogleUpdaterSetup-151.0.7910.0.exe'                        = 'Installers\ChromiumSetup\Google.GoogleUpdater\151.0.7910.0\GoogleUpdaterSetup-151.0.7910.0.exe'
  'GoogleUpdateSetup-1.3.35.452.exe'                           = 'Installers\ChromiumSetup\Google.GoogleUpdater\1.3.35.452\GoogleUpdateSetup-1.3.35.452.exe'
  'GoogleUpdateSetup-1.3.36.372.exe'                           = 'Installers\ChromiumSetup\Google.GoogleUpdater\1.3.36.372\GoogleUpdateSetup-1.3.36.372.exe'
  'MicrosoftEdgeWebView2Bootstrapper.exe'                      = 'Installers\ChromiumSetup\Microsoft.EdgeWebView2Runtime\Current\MicrosoftEdgeWebView2Bootstrapper.exe'
  'MicrosoftEdgeWebView2RuntimeInstallerX64-150.0.4078.65.exe' = 'Installers\ChromiumSetup\Microsoft.EdgeWebView2Runtime\150.0.4078.65\MicrosoftEdgeWebView2RuntimeInstallerX64-150.0.4078.65.exe'
  'Vivaldi.8.2.4106.4.x64.exe'                                 = 'Installers\ChromiumSetup\Vivaldi.Vivaldi\8.2.4106.4\Vivaldi.8.2.4106.4.x64.exe'
  'Zoho.Ulaa-150.0.7871.129.exe'                               = 'Installers\ChromiumSetup\Zoho.Ulaa\150.0.7871.129\Zoho.Ulaa-150.0.7871.129.exe'

  # Inno Setup
  'Argente.DataShredder.x64.exe'                               = 'Installers\Inno\Argente.DataShredder\Current\Argente.DataShredder.x64.exe'
  'BankLinkBooks.exe'                                          = 'Installers\Inno\MYOB.BankLinkBooks\Current\BankLinkBooks.exe'
  'innosetup-7.0.2-x64.exe'                                    = 'Builders\Inno\7.0.2\OfficialInstaller\innosetup-7.0.2-x64.exe'
  'kiro-ide-1.0.138-stable-win32-x64.exe'                      = 'Installers\Inno\Amazon.Kiro\1.0.138\kiro-ide-1.0.138-stable-win32-x64.exe'
  'loot_0.26.0-win64.exe'                                      = 'Installers\Inno\LOOT.LOOT\0.26.0\loot_0.26.0-win64.exe'
  'nomachine_9.8.2_1_x64.exe'                                  = 'Installers\Inno\NoMachine.NoMachine\9.8.2.1\nomachine_9.8.2_1_x64.exe'
  'nomachine_9.8.2_1_x86.exe'                                  = 'Installers\Inno\NoMachine.NoMachine\9.8.2.1\nomachine_9.8.2_1_x86.exe'
  'PixPin_win_3.4.2.1.exe'                                     = 'Installers\Inno\PixPin.PixPin.Beta\3.4.2.1\PixPin_win_3.4.2.1.exe'
  'QoderUserSetup-1.14.1-x64.exe'                              = 'Installers\Inno\Alibaba.Qoder\1.14.1\QoderUserSetup-1.14.1-x64.exe'
  'VUSC_setup_709.zip'                                         = 'Installers\Inno\VUSC.VUSC\7.09\VUSC_setup_709.zip'
  'WinSCP-6.5.6-Setup.exe'                                     = 'Installers\Inno\WinSCP.WinSCP\6.5.6\WinSCP-6.5.6-Setup.exe'

  # Install4j and InstallAnywhere
  'install4j_windows_3_2_5.exe'                                = 'Builders\Install4j\3.2.5\OfficialInstaller\install4j_windows_3_2_5.exe'
  'install4j_windows-x64_4_1.exe'                              = 'Builders\Install4j\4.1\OfficialInstaller\install4j_windows-x64_4_1.exe'
  'install4j_windows-x64_4_2_8.exe'                            = 'Builders\Install4j\4.2.8\OfficialInstaller\install4j_windows-x64_4_2_8.exe'
  'install4j_windows-x64_5_0_11.exe'                           = 'Builders\Install4j\5.0.11\OfficialInstaller\install4j_windows-x64_5_0_11.exe'
  'install4j_windows-x64_5_1_15.exe'                           = 'Builders\Install4j\5.1.15\OfficialInstaller\install4j_windows-x64_5_1_15.exe'
  'install4j_windows-x64_6_1_6.exe'                            = 'Builders\Install4j\6.1.6\OfficialInstaller\install4j_windows-x64_6_1_6.exe'
  'install4j_windows-x64_7_0_12.exe'                           = 'Builders\Install4j\7.0.12\OfficialInstaller\install4j_windows-x64_7_0_12.exe'
  'install4j_windows-x64_8_0_11.exe'                           = 'Builders\Install4j\8.0.11\OfficialInstaller\install4j_windows-x64_8_0_11.exe'
  'install4j_windows-x64_9_0_7.exe'                            = 'Builders\Install4j\9.0.7\OfficialInstaller\install4j_windows-x64_9_0_7.exe'
  'install4j_windows-x64_10_0_9.exe'                           = 'Builders\Install4j\10.0.9\OfficialInstaller\install4j_windows-x64_10_0_9.exe'
  'install4j_windows-x64_11_0_5.exe'                           = 'Builders\Install4j\11.0.5\OfficialInstaller\install4j_windows-x64_11_0_5.exe'
  'install4j_windows-x64_12_0_5.exe'                           = 'Builders\Install4j\12.0.5\OfficialInstaller\install4j_windows-x64_12_0_5.exe'
  'install4j_windows-x64_13_0_2.exe'                           = 'Builders\Install4j\13.0.2\OfficialInstaller\install4j_windows-x64_13_0_2.exe'
  'FlowJo-Win64-10.10.0.exe'                                   = 'Installers\InstallAnywhere\FlowJo.FlowJo\10.10.0\FlowJo-Win64-10.10.0.exe'
  'PortSwigger.BurpSuite.Community-2026.3.3.exe'               = 'Installers\Install4j\PortSwigger.BurpSuite.Community\2026.3.3\PortSwigger.BurpSuite.Community-2026.3.3.exe'
  'Qoppa.PDFStudio-2024.0.1.exe'                               = 'Installers\Install4j\Qoppa.PDFStudio\2024.0.1\Qoppa.PDFStudio-2024.0.1.exe'
  'ZAP_2_17_0_windows.exe'                                     = 'Installers\Install4j\ZAP.ZAP\2.17.0\ZAP_2_17_0_windows.exe'

  # MicaSetup
  'MicaSetup-v1.0.0.exe'                                       = 'Installers\MicaSetup\MicaSetup.MicaSetup\1.0.0\MicaSetup-v1.0.0.exe'
  'MicaSetup-v1.3.0.exe'                                       = 'Installers\MicaSetup\MicaSetup.MicaSetup\1.3.0\MicaSetup-v1.3.0.exe'
  'MicaSetup-v2.0.0.exe'                                       = 'Installers\MicaSetup\MicaSetup.MicaSetup\2.0.0\MicaSetup-v2.0.0.exe'
  'MicaSetup-v2.5.4.exe'                                       = 'Installers\MicaSetup\MicaSetup\2.5.4\MicaSetup-v2.5.4.exe'

  # DeployMaster and InstallMate
  'Setup Brinno Video Player.exe'                              = 'Installers\DeployMaster\Brinno.BrinnoVideoPlayer\1.139.00\Setup Brinno Video Player.exe'
  'PoP8Setup.exe'                                              = 'Installers\InstallMate\Tarma.PublishOrPerish\8\PoP8Setup.exe'

  # InstallShield
  'AFAS.ProfitCommunicationCenter.7.exe'                       = 'Installers\InstallShield\AFAS.ProfitCommunicationCenter.7\7.00\AFAS.ProfitCommunicationCenter.7.exe'
  'AFAS.ProfitCommunicationCenter.8.exe'                       = 'Installers\InstallShield\AFAS.ProfitCommunicationCenter.8\Current\AFAS.ProfitCommunicationCenter.8.exe'
  'antrad_setup.exe'                                           = 'Installers\InstallShield\AntRad.AntRad\Current\antrad_setup.exe'
  'AVerTouch.zip'                                              = 'Installers\InstallShield\AVer.AVerTouch\Current\AVerTouch.zip'
  'CastleDriver.zip'                                           = 'Installers\InstallShield\Linkly.CastleDriver\Current\CastleDriver.zip'
  'CSP_504w_setup.exe'                                         = 'Installers\InstallShield\Celsys.ClipStudioPaint\5.0.4\CSP_504w_setup.exe'
  'DDPM-Setup_2.3.0.17.exe'                                    = 'Installers\InstallShield\Dell.DisplayAndPeripheralManager\2.3.0.17\DDPM-Setup_2.3.0.17.exe'
  'dnc2_1.5.55_U.exe'                                          = 'Installers\InstallShield\Sharp.DisplayConnect\1.5.55\dnc2_1.5.55_U.exe'
  'dnc3_1.1.1.6.exe'                                           = 'Installers\InstallShield\Sharp.DisplayConnect\1.1.1.6\dnc3_1.1.1.6.exe'
  'Install_PRNclient_FR_2023.0.1.2_win32.exe'                  = 'Installers\InstallShield\IndexEducation.PRONOTE.Client\2023.0.1.2\Install_PRNclient_FR_2023.0.1.2_win32.exe'
  'Install_PRNclient_FR_2023.0.1.2_win64.exe'                  = 'Installers\InstallShield\IndexEducation.PRONOTE.Client\2023.0.1.2\Install_PRNclient_FR_2023.0.1.2_win64.exe'
  'PenSoftware_v3_9_2_2_jp_Setup.exe'                          = 'Installers\InstallShield\Sharp.PenSoftware\3.9.2.2\PenSoftware_v3_9_2_2_jp_Setup.exe'
  'PenSoftware_v3_9_2_2_jp.zip'                                = 'Installers\InstallShield\Sharp.PenSoftware\3.9.2.2\PenSoftware_v3_9_2_2_jp.zip'
  'SketchUpViewer-2022-0-316-108.exe'                          = 'Installers\InstallShield\Trimble.SketchUpViewer\2022.0.316.108\SketchUpViewer-2022-0-316-108.exe'
  'TachoFileViewer_3_40.exe'                                   = 'Installers\InstallShield\TachoFileViewer.TachoFileViewer\3.40\TachoFileViewer_3_40.exe'
  'Thorlabs.ThorlabsDeviceSDK.zip'                             = 'Installers\InstallShield\Thorlabs.ThorlabsDeviceSDK\Current\Thorlabs.ThorlabsDeviceSDK.zip'
  'Thorlabs.TSP01.zip'                                         = 'Installers\InstallShield\Thorlabs.TSP01\Current\Thorlabs.TSP01.zip'
  'U90Ladder_6_6_45.exe'                                       = 'Installers\InstallShield\Unitronics.U90Ladder\6.6.45\U90Ladder_6_6_45.exe'
  'Vertexshare.WebpConverter.exe'                              = 'Installers\InstallShield\Vertexshare.WebpConverter\Current\Vertexshare.WebpConverter.exe'
  'WiFi Sensor Software.exe'                                   = 'Installers\InstallShield\FilesThruTheAir.WiFiSensorSoftware\Current\WiFi Sensor Software.exe'

  # MSI, WiX, and MSP
  'AdvancedInstaller-6.4.msi'                                  = 'Builders\AdvancedInstaller\6.4\OfficialInstaller\AdvancedInstaller-6.4.msi'
  'AdvancedInstaller-8.6.msi'                                  = 'Builders\AdvancedInstaller\8.6\OfficialInstaller\AdvancedInstaller-8.6.msi'
  'AdvancedInstaller-23.9.msi'                                 = 'Builders\AdvancedInstaller\23.9\OfficialInstaller\AdvancedInstaller-23.9.msi'
  'BeidViewer-5.1.31.6342.msi'                                 = 'Installers\MSI\BelgianGovernment.eIDViewer\5.1.31.6342\BeidViewer-5.1.31.6342.msi'
  'BoxDrive-2.51.234.msi'                                      = 'Installers\MSI\Box.Box\2.51.234\BoxDrive-2.51.234.msi'
  'BrowserStackLocal.msi'                                      = 'Installers\MSI\BrowserStack.BrowserStackLocal\Current\BrowserStackLocal.msi'
  'CatoNetworks.CatoClient.x64.msi'                            = 'Installers\MSI\CatoNetworks.CatoClient\Current\CatoNetworks.CatoClient.x64.msi'
  'Cisco.NetworkRecordingPlayer.x86.msi'                       = 'Installers\MSI\Cisco.NetworkRecordingPlayer\Current\Cisco.NetworkRecordingPlayer.x86.msi'
  'Cribl.CriblEdge.x64.msi'                                    = 'Installers\MSI\Cribl.CriblEdge\Current\Cribl.CriblEdge.x64.msi'
  'CrisisGo.CrisisGo.x86.msi'                                  = 'Installers\MSI\CrisisGo.CrisisGo\Current\CrisisGo.CrisisGo.x86.msi'
  'draw.io-30.2.6.msi'                                         = 'Installers\MSI\JGraph.Draw\30.2.6\draw.io-30.2.6.msi'
  'eposconnect_8.5.0_msi.zip'                                  = 'Installers\MSI\EPOS.EPOSConnect\8.5.0\eposconnect_8.5.0_msi.zip'
  'Figma-125.8.5.msi'                                          = 'Installers\MSI\Figma.Figma\125.8.5\Figma-125.8.5.msi'
  'GoogleChromeStandaloneEnterprise-current-x64.msi'           = 'Installers\MSI\Google.Chrome\Current\GoogleChromeStandaloneEnterprise-current-x64.msi'
  'Housatonic.ProjectViewer365.x64.msi'                        = 'Installers\MSI\Housatonic.ProjectViewer365\Current\Housatonic.ProjectViewer365.x64.msi'
  'PaloAltoNetworks.PrismaAccessBrowser.x64.msi'               = 'Installers\MSI\PaloAltoNetworks.PrismaAccessBrowser\Current\PaloAltoNetworks.PrismaAccessBrowser.x64.msi'
  'Patch-1.33.107.0-release.x64.msp'                           = 'Installers\MSI\Macrobond.Macrobond\1.33.107.0\Patch-1.33.107.0-release.x64.msp'
  'prisma-arm64.msi'                                           = 'Installers\MSI\PaloAltoNetworks.PrismaAccessBrowser\Current\prisma-arm64.msi'
  'ProjectViewer_365_PC_26.4.1290.msi'                         = 'Installers\MSI\Housatonic.ProjectViewer365\26.4.1290\ProjectViewer_365_PC_26.4.1290.msi'
  'ScreenToGif-2.43.2-x64.msi'                                 = 'Installers\MSI\NickeManarin.ScreenToGif\2.43.2\ScreenToGif-2.43.2-x64.msi'
  'Talkdesk-3.1.0.msi'                                         = 'Installers\MSI\Talkdesk.Talkdesk\3.1.0\Talkdesk-3.1.0.msi'
  'Tower-13.1.576.msi'                                         = 'Installers\MSI\SaaSGroup.Tower\13.1.576\Tower-13.1.576.msi'
  'Tulip Player Setup.msi'                                     = 'Installers\MSI\Tulip.TulipPlayer\Current\Tulip Player Setup.msi'
  'Vurbo.ai_1.12.2.2.msi'                                      = 'Installers\MSI\IPEVO.Vurbo-ai\1.12.2.2\Vurbo.ai_1.12.2.2.msi'

  # MSIX/AppX
  'Lamina_11.28000.16.0_x64.msix'                              = 'Installers\MSIX\Chill-Astro.LaminaCalculator\11.28000.16.0\Lamina_11.28000.16.0_x64.msix'
  'XmlNotepadPackage_2.9.0.17_AnyCPU.msixbundle'               = 'Installers\MSIX\Microsoft.XMLNotepad\2.9.0.17\XmlNotepadPackage_2.9.0.17_AnyCPU.msixbundle'

  # NSIS
  'AionUi-2.1.42-win-x64.exe'                                  = 'Installers\NSIS\HaiYing.AionUi\2.1.42\AionUi-2.1.42-win-x64.exe'
  'Aircall-Workspace-1.15.13-x64.exe'                          = 'Installers\NSIS\Aircall.AircallWorkspace\1.15.13\Aircall-Workspace-1.15.13-x64.exe'
  'alist-desktop_3.60.0_x64-setup.exe'                         = 'Installers\NSIS\AlistGo.AListDesktop\3.60.0\alist-desktop_3.60.0_x64-setup.exe'
  'BeeDrive-2.0.3-20301-x64.exe'                               = 'Installers\NSIS\Synology.BeeDrive\2.0.3.20301\BeeDrive-2.0.3-20301-x64.exe'
  'BitComet_2.21_setup.exe'                                    = 'Installers\NSIS\CometNetwork.BitComet\2.21\BitComet_2.21_setup.exe'
  'Bitwarden-Portable-2026.6.1.exe'                            = 'Installers\NSIS\Bitwarden.Bitwarden.Portable\2026.6.1\Bitwarden-Portable-2026.6.1.exe'
  'BongoCat_1.1.0_x64-setup.exe'                               = 'Installers\NSIS\ayangweb.BongoCat\1.1.0\BongoCat_1.1.0_x64-setup.exe'
  'CCFLink_v7.7.0.80131.exe'                                   = 'Installers\NSIS\CCF.CCFLink\7.7.0.80131\CCFLink_v7.7.0.80131.exe'
  'Clash.Verge_2.5.2_x64-setup.exe'                            = 'Installers\NSIS\ClashVergeRev.ClashVergeRev\2.5.2\Clash.Verge_2.5.2_x64-setup.exe'
  'codeg_0.21.5_x64-setup.exe'                                 = 'Installers\NSIS\XinTaoFei.Codeg\0.21.5\codeg_0.21.5_x64-setup.exe'
  'dbeaver-ce-26.1.3-windows-x86_64.exe'                       = 'Installers\NSIS\DBeaver.DBeaver.Community\26.1.3\dbeaver-ce-26.1.3-windows-x86_64.exe'
  'Exr-IO_2.06.00.exe'                                         = 'Installers\NSIS\3d-io.Exr-IO\2.06.00\Exr-IO_2.06.00.exe'
  'fdm_x64_setup-6.34.4.6974.exe'                              = 'Installers\NSIS\SoftDeluxe.FreeDownloadManager\6.34.4.6974\fdm_x64_setup-6.34.4.6974.exe'
  'FeiLian_Windows_x86_v3.2.16_r4828_a60997.exe'               = 'Installers\NSIS\ByteDance.FeiLian\3.2.16\FeiLian_Windows_x86_v3.2.16_r4828_a60997.exe'
  'fluent-bit-5.1.0-win64.exe'                                 = 'Installers\NSIS\Fluent.FluentBit\5.1.0\fluent-bit-5.1.0-win64.exe'
  'GoToSetup-4.19.1.exe'                                       = 'Installers\NSIS\GoTo.GoTo\4.19.1\GoToSetup-4.19.1.exe'
  'Google-Antigravity-2.8.1-x64.exe'                           = 'Installers\NSIS\Google.Antigravity\2.8.1\Google-Antigravity-2.8.1-x64.exe'
  'libjpeg-turbo-3.2.0-gcc-x64.exe'                            = 'Installers\NSIS\libjpeg-turbo.libjpeg-turbo.GCC\3.2.0\libjpeg-turbo-3.2.0-gcc-x64.exe'
  'libjpeg-turbo-3.2.0-gcc-x86.exe'                            = 'Installers\NSIS\libjpeg-turbo.libjpeg-turbo.GCC\3.2.0\libjpeg-turbo-3.2.0-gcc-x86.exe'
  'libjpeg-turbo-3.2.0-vc-arm64.exe'                           = 'Installers\NSIS\libjpeg-turbo.libjpeg-turbo.VC\3.2.0\libjpeg-turbo-3.2.0-vc-arm64.exe'
  'libjpeg-turbo-3.2.0-vc-x64.exe'                             = 'Installers\NSIS\libjpeg-turbo.libjpeg-turbo.VC\3.2.0\libjpeg-turbo-3.2.0-vc-x64.exe'
  'libjpeg-turbo-3.2.0-vc-x86.exe'                             = 'Installers\NSIS\libjpeg-turbo.libjpeg-turbo.VC\3.2.0\libjpeg-turbo-3.2.0-vc-x86.exe'
  'RedPanda.C++.3.4.win64.MinGW64_11.5.0.Setup.exe'            = 'Installers\NSIS\RoyQu.RedPanda-C++\3.4\RedPanda.C++.3.4.win64.MinGW64_11.5.0.Setup.exe'
  'TencentMeeting_0300000000_3.44.10.457_x86_64.publish.exe'   = 'Installers\NSIS\Tencent.TencentMeeting\3.44.10.457\TencentMeeting_0300000000_3.44.10.457_x86_64.publish.exe'
  'TencentMeeting_3.44.10.457_x64.exe'                         = 'Installers\NSIS\Tencent.TencentMeeting\3.44.10.457\TencentMeeting_3.44.10.457_x64.exe'
  'TK-Copilot.Setup.1.8.82.exe'                                = 'Installers\NSIS\TK-Copilot.TK-Copilot\1.8.82\TK-Copilot.Setup.1.8.82.exe'
  'TranslatorX_26.1.1_x64-setup.exe'                           = 'Installers\NSIS\AgilentTechnologies.TranslatorX\26.1.1\TranslatorX_26.1.1_x64-setup.exe'
  'UURemote_Setup_4.34.0.8979.exe'                             = 'Installers\NSIS\NetEase.UURemote\4.34.0.8979\UURemote_Setup_4.34.0.8979.exe'
  'vivo-OfficeKit-6.7.3.0.exe'                                 = 'Installers\NSIS\vivo.OfficeKit\6.7.3.0\vivo-OfficeKit-6.7.3.0.exe'
  '115br_v36.0.1.exe'                                          = 'Installers\NSIS\115.115Chrome\36.0.1\115br_v36.0.1.exe'
  'WingFtpServer-8.2.1.exe'                                    = 'Installers\NSIS\WingFtpServer.WingFtpServer\8.2.1\WingFtpServer-8.2.1.exe'
  'WingGateway-1.1.2.exe'                                      = 'Installers\NSIS\WingGateway.WingGateway\1.1.2\WingGateway-1.1.2.exe'
  'WorkBuddy-win32-x64-user-5.3.5.34189228-8044e898.exe'       = 'Installers\NSIS\Tencent.WorkBuddy\5.3.5.34189228\WorkBuddy-win32-x64-user-5.3.5.34189228-8044e898.exe'
  'yuanfudao-student-7.27.0.22424-installer-x64.exe'           = 'Installers\NSIS\Yuanfudao.Yuanfudao\7.27.0.22424\yuanfudao-student-7.27.0.22424-installer-x64.exe'

  # Other installer families
  'AkashaNavigator.Install.1.4.0.exe'                          = 'Installers\Kachina\AkashaNavigator.AkashaNavigator\1.4.0\AkashaNavigator.Install.1.4.0.exe'
  'BetterGI.Install.0.40.0.exe'                                = 'Installers\Kachina\babalae.BetterGI\0.40.0\BetterGI.Install.0.40.0.exe'
  'BetterGI.Install.0.63.0.exe'                                = 'Installers\Kachina\babalae.BetterGI\0.63.0\BetterGI.Install.0.63.0.exe'
  'CrossPlusA.Balabolka.setup.exe'                             = 'Installers\CreateInstall\CrossPlusA.Balabolka\Current\CrossPlusA.Balabolka.setup.exe'
  'Lakes_SCREENView_4.0.1.exe'                                 = 'Installers\WinRarSfx\Lakes.SCREENView\4.0.1\Lakes_SCREENView_4.0.1.exe'
  'NM34_x64.exe'                                               = 'Installers\IExpress\Microsoft.NetMon\3.4\NM34_x64.exe'
  'Nessus-10.12.3-x64.msi'                                     = 'Installers\MSI\Tenable.Nessus\10.12.3\Nessus-10.12.3-x64.msi'
  'Novostrim.CreateInstall.8.11.2.exe'                         = 'Builders\CreateInstall\8.11.2\OfficialInstaller\Novostrim.CreateInstall.8.11.2.exe'
  'RARLab_WinRAR_7.23.0_x64.exe'                               = 'Installers\WinRarSfx\RARLab.WinRAR\7.23.0\RARLab_WinRAR_7.23.0_x64.exe'

  # Qt Installer Framework
  'msys2-x86_64-latest.exe'                                    = 'Installers\QtInstallerFramework\MSYS2.MSYS2\Current\msys2-x86_64-latest.exe'
  'qt-ifw-1.3.0.exe'                                           = 'Builders\QtInstallerFramework\1.3.0\OfficialInstaller\qt-ifw-1.3.0.exe'
  'qt-ifw-1.5.0.exe'                                           = 'Builders\QtInstallerFramework\1.5.0\OfficialInstaller\qt-ifw-1.5.0.exe'
  'qt-ifw-2.0.5.exe'                                           = 'Builders\QtInstallerFramework\2.0.5\OfficialInstaller\qt-ifw-2.0.5.exe'
  'qt-ifw-3.2.2.exe'                                           = 'Builders\QtInstallerFramework\3.2.2\OfficialInstaller\qt-ifw-3.2.2.exe'
  'qt-ifw-4.0.0.exe'                                           = 'Builders\QtInstallerFramework\4.0.0\OfficialInstaller\qt-ifw-4.0.0.exe'
  'qt-ifw-4.2.0.exe'                                           = 'Builders\QtInstallerFramework\4.2.0\OfficialInstaller\qt-ifw-4.2.0.exe'
  'qt-ifw-4.11.0.exe'                                          = 'Builders\QtInstallerFramework\4.11.0\OfficialInstaller\qt-ifw-4.11.0.exe'
  'qtlinguistinstaller-5.12.2.exe'                             = 'Installers\QtInstallerFramework\Qt.QtLinguist\5.12.2\qtlinguistinstaller-5.12.2.exe'
  'reMarkable-3.8.0.810-win64-LDv4m9Vntg.exe'                  = 'Installers\QtInstallerFramework\reMarkable.reMarkableCompanionApp\3.8.0.810\reMarkable-3.8.0.810-win64-LDv4m9Vntg.exe'

  # Squirrel and Velopack
  'AppeeeSetup.exe'                                            = 'Installers\Squirrel\Appeee.Appeee\Current\AppeeeSetup.exe'
  'Chime-5.23.32138.exe'                                       = 'Installers\Squirrel\Amazon.Chime\5.23.32138\Chime-5.23.32138.exe'
  'DialpadSetup-2605.1.0_x64.exe'                              = 'Installers\Squirrel\Dialpad.Dialpad\2605.1.0\DialpadSetup-2605.1.0_x64.exe'
  'DiscordSetup-1.0.9244.exe'                                  = 'Installers\Squirrel\Discord.Discord\1.0.9244\DiscordSetup-1.0.9244.exe'
  'Figma-126.6.12.exe'                                         = 'Installers\Squirrel\Figma.Figma\126.6.12\Figma-126.6.12.exe'
  'SlackSetup-4.50.143.exe'                                    = 'Installers\Squirrel\SlackTechnologies.Slack\4.50.143\SlackSetup-4.50.143.exe'
  'SourceTreeSetup-3.4.31.exe'                                 = 'Installers\Squirrel\Atlassian.Sourcetree\3.4.31\SourceTreeSetup-3.4.31.exe'
  'TogglTrack-windows64.exe'                                   = 'Installers\Squirrel\Toggl.TogglTrack\Current\TogglTrack-windows64.exe'
  'Tower-13.1.576.exe'                                         = 'Installers\Squirrel\SaaSGroup.Tower\13.1.576\Tower-13.1.576.exe'

  # Tauri and portable assets
  'Clash.Verge_1.7.7_arm64_portable.zip'                       = 'Installers\Portable\ClashVergeRev.ClashVergeRev\1.7.7\Clash.Verge_1.7.7_arm64_portable.zip'
  'Clash.Verge_1.7.7_x64_portable.zip'                         = 'Installers\Portable\ClashVergeRev.ClashVergeRev\1.7.7\Clash.Verge_1.7.7_x64_portable.zip'
  'Clash.Verge_1.7.7_x86_portable.zip'                         = 'Installers\Portable\ClashVergeRev.ClashVergeRev\1.7.7\Clash.Verge_1.7.7_x86_portable.zip'
  'Readest_0.11.20_arm64-portable.exe'                         = 'Installers\Portable\chrox.Readest\0.11.20\Readest_0.11.20_arm64-portable.exe'
  'Readest_0.11.20_x64-portable.exe'                           = 'Installers\Portable\chrox.Readest\0.11.20\Readest_0.11.20_x64-portable.exe'
  'Readest_0.11.20_x64-setup.exe'                              = 'Installers\NSIS\chrox.Readest\0.11.20\Readest_0.11.20_x64-setup.exe'
  'Reader-v1.4.3-windows-x64-setup.exe'                        = 'Installers\NSIS\hadc188.Reader\1.4.3\Reader-v1.4.3-windows-x64-setup.exe'
  'Yaak_2026.4.0_x64-setup.exe'                                = 'Installers\NSIS\MountainLoop.Yaak\2026.4.0\Yaak_2026.4.0_x64-setup.exe'
  'ChatWise_0.9.76_x64-setup.exe'                              = 'Installers\NSIS\ChatWise.ChatWise\0.9.76\ChatWise_0.9.76_x64-setup.exe'
  'Antigravity.Tools_3.3.15_x64-setup.exe'                     = 'Installers\NSIS\AntigravityTools.AntigravityTools\3.3.15\Antigravity.Tools_3.3.15_x64-setup.exe'

  # Zero Install
  '0install.exe'                                               = 'Installers\ZeroInstall\ZeroInstall.ZeroInstall\2.29.0\0install.exe'
  'DeepLSetup.exe'                                             = 'Installers\ZeroInstall\DeepL.DeepL\Current\DeepLSetup.exe'
  'zero-install.exe'                                           = 'Installers\ZeroInstall\ZeroInstall.ZeroInstall\2.29.0\zero-install.exe'

  # Historical compiler installers are curated builder evidence.
  'innosetup-6.0.0-beta.exe'                                   = 'Builders\Inno\6.0.0-beta\OfficialInstaller\innosetup-6.0.0-beta.exe'
  'innosetup-6.5.0.exe'                                        = 'Builders\Inno\6.5.0\OfficialInstaller\innosetup-6.5.0.exe'
  'innosetup-6.7.0.exe'                                        = 'Builders\Inno\6.7.0\OfficialInstaller\innosetup-6.7.0.exe'
  'isdsetup.1.5.exe'                                           = 'Builders\Inno\5.5.7\DecompilerInstaller\isdsetup.1.5.exe'
  'isetup-5.1.2-beta.exe'                                      = 'Builders\Inno\5.1.2-beta\OfficialInstaller\isetup-5.1.2-beta.exe'
  'isetup-5.4.2-a.exe'                                         = 'Builders\Inno\5.4.2\OfficialInstaller\isetup-5.4.2-a.exe'
  'isetup-5.4.2-u.exe'                                         = 'Builders\Inno\5.4.2\OfficialInstaller\isetup-5.4.2-u.exe'
  'nsis203.exe'                                                = 'Builders\NSIS\2.03\OfficialInstaller\nsis203.exe'
  'nsis204.exe'                                                = 'Builders\NSIS\2.04\OfficialInstaller\nsis204.exe'
  'nsis-2.25-setup.exe'                                        = 'Builders\NSIS\2.25\OfficialInstaller\nsis-2.25-setup.exe'
  'nsis-2.26-setup.exe'                                        = 'Builders\NSIS\2.26\OfficialInstaller\nsis-2.26-setup.exe'
  'nsis-2.33-Unicode-setup.exe'                                = 'Builders\NSIS\2.33-Unicode\OfficialInstaller\nsis-2.33-Unicode-setup.exe'
  'nsis-2.46-setup.exe'                                        = 'Builders\NSIS\2.46\OfficialInstaller\nsis-2.46-setup.exe'
  'nsis-2.46.2-Unicode-setup.exe'                              = 'Builders\NSIS\2.46.2-Unicode\OfficialInstaller\nsis-2.46.2-Unicode-setup.exe'
  'nsis-2.46.3-Unicode-setup.exe'                              = 'Builders\NSIS\2.46.3-Unicode\OfficialInstaller\nsis-2.46.3-Unicode-setup.exe'
  'nsis-2.51-setup.exe'                                        = 'Builders\NSIS\2.51\OfficialInstaller\nsis-2.51-setup.exe'
  'PortableApps.com_Platform_Setup_30.4.2.paf.exe'             = 'Installers\NSIS\PortableApps.PortableAppsPlatform\30.4.2\PortableApps.com_Platform_Setup_30.4.2.paf.exe'

  # Cross-family bridge and regression fixtures
  'draw.io-30.2.6-windows-installer.exe'                       = 'Installers\AdvancedInstaller\JGraph.Draw\30.2.6\draw.io-30.2.6-windows-installer.exe'
  'GameSir-Connect-Setup-1.6.8.exe'                            = 'Installers\NSIS\GameSir.GameSirConnect\1.6.8\GameSir-Connect-Setup-1.6.8.exe'
  'GameSir-T4k-App-Setup-0.3.3.exe'                            = 'Installers\NSIS\GameSir.T4kApp\0.3.3\GameSir-T4k-App-Setup-0.3.3.exe'
  'GDevelop-5-Setup-5.6.273.exe'                               = 'Installers\NSIS\GDevelop.GDevelop\5.6.273\GDevelop-5-Setup-5.6.273.exe'
  'NeatReader Setup 9.0.10.exe'                                = 'Installers\NSIS\NeatReader.NeatReader\9.0.10\NeatReader Setup 9.0.10.exe'
  'Obsidian-1.12.7.exe'                                        = 'Installers\NSIS\Obsidian.Obsidian\1.12.7\Obsidian-1.12.7.exe'
  'OutCALL-2.0.exe'                                            = 'Installers\SetupFactory\BicomSystems.OutCALL\2.0\OutCALL-2.0.exe'
  'Communicator-7.6.0.exe'                                     = 'Installers\SetupFactory\BicomSystems.Communicator\7.6.0\Communicator-7.6.0.exe'
  'gloCOM-7.6.0.4.exe'                                         = 'Installers\SetupFactory\BicomSystems.gloCOM\7.6.0.4\gloCOM-7.6.0.4.exe'
  'SafeguardPDFViewer_v3.exe'                                  = 'Installers\SetupFactory\Locklizard.SafeguardPDFViewer\3.0.2.231\SafeguardPDFViewer_v3.exe'
  'Reasonix-windows-amd64-installer-1.17.13.exe'               = 'Installers\NSIS\ESEngine.ReasonixDesktop\1.17.13\Reasonix-windows-amd64-installer-1.17.13.exe'
  'TI-Connect-4.0.0.218.exe'                                   = 'Installers\Wise\TexasInstruments.TIConnect\4.0.0.218\TI-Connect-4.0.0.218.exe'
}
